services:
  - type: web
    name: whatsapp-bot-grsia
    runtime: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: SECRET
        value: 123321597Davi
      - key: ADMIN_NUMBERS
        value: 5511932010789,5511983398414
      - key: INSTAGRAM_URL
        value: https://www.instagram.com/grsia.br/
    plan: free